In [1]:
import pandas as pd
from scikit_posthocs import posthoc_dunn as pdunn

In [2]:
data = pd.read_excel("/Users/adrienkouanda/Documents/ETUDIANTS/EDJENGUELE/data_1.xlsx")

In [3]:
data

,Numéro_de_fiche,Age_en_année,Tranche_age,Sexe,Diabète,HTA,Maladie_rénale_chronique,Infection_a_VIH,Cancer,Hépatite,...,tranche_délai_de_trachéotomie_codée,Sortie_contre_avis_médical,Transfert_dans_un_autre_service,Décès,Sortie_pour_domicile,@_index,Tranches_ventilation,Tranche_trachetomie,Tranche_hospi,Tranch_Qsofa
0,1,62,58-67,Masculin,Non,Oui,Oui,Non,Non,Non,...,NaN,Non,Non,Oui,Non,52,< 7 jours,NaN,<10,<2
1,2,46,38-47,Féminin,Non,Non,Oui,Non,Non,Non,...,NaN,Non,Non,Oui,Non,53,< 7 jours,NaN,<10,>=2
2,3,60,58-67,Masculin,Non,Non,Non,Non,Non,Non,...,NaN,Non,Oui,Non,Non,54,< 7 jours,NaN,<10,>=2
3,4,58,58-67,Masculin,Oui,Oui,Non,Non,Non,Non,...,NaN,Non,Oui,Non,Non,55,< 7 jours,NaN,<10,<2
4,5,73,>=68,Féminin,Non,Non,Non,Non,Non,Non,...,NaN,Non,Non,Oui,Non,56,< 7 jours,NaN,<10,<2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,388,55,48-57,Masculin,Non,Non,Non,Non,Non,Non,...,NaN,Non,Non,Oui,Non,437,7-14 jours,NaN,10-20,>=2
386,392,51,48-57,Masculin,Non,Oui,Non,Non,Non,Non,...,NaN,Non,Oui,Non,Non,438,7-14 jours,NaN,10-20,<2
387,390,42,38-47,Féminin,Non,Non,Non,Oui,Non,Non,...,NaN,Non,Non,Oui,Non,439,< 7 jours,NaN,<10,>=2
388,391,51,48-57,Féminin,Non,Non,Non,Non,Non,Non,...,NaN,Non,Oui,Non,Non,440,< 7 jours,NaN,<10,<2
389,389,30,28-37,Masculin,Non,Non,Non,Non,Non,Non,...,NaN,Non,Oui,Non,Non,441,< 7 jours,NaN,<10,<2

In [4]:
res = pdunn(data,val_col="Age_en_année",group_col="Tranche_age")

In [5]:
res

,18-27,28-37,38-47,48-57,58-67,>=68
18-27,1.000000e+00,1.195763e-01,2.325452e-04,2.257196e-12,3.495948e-30,4.963221e-50
28-37,1.195763e-01,1.000000e+00,3.898786e-02,7.854623e-08,7.377944e-23,3.507141e-41
38-47,2.325452e-04,3.898786e-02,1.000000e+00,5.533470e-04,7.641016e-17,8.455712e-35
48-57,2.257196e-12,7.854623e-08,5.533470e-04,1.000000e+00,9.797252e-08,6.041519e-23
58-67,3.495948e-30,7.377944e-23,7.641016e-17,9.797252e-08,1.000000e+00,3.560169e-07
>=68,4.963221e-50,3.507141e-41,8.455712e-35,6.041519e-23,3.560169e-07,1.000000e+00

In [1]:
"""rien du tout """ + """   
hghg
hghg
jkhkjh

"""

'rien du tout    \nhghg\nhghg\njkhkjh\n\n'